---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
# devtools::load_all("~/ACTIONet/")
# install.packages("~/ACTIONet/", repos = NULL)
library(ACTIONet)


# source("~/snSZ_v2/functions.R")

```

```{r}
combined.ace = readr::read_rds("~/BD/results/datasets/ACTIONet_v2.rds")

cols= readr::read_rds("~/results/datasets/celltype_colors.rds")

celltypes.df = loadDataset("celltype_stats", dataset.path = file.path(tables.path, "rds"))
celltype_colors = celltypes.df$color
names(celltype_colors) = celltypes.df$celltype



```


```{r}
plot.ACTIONet(combined.ace, combined.ace$Celltype)
plot.ACTIONet(combined.ace, combined.ace$Celltype_inferred)

```
```{r}
combined.ace = normalize.ace(combined.ace)
combined.ace = reduce.ace(combined.ace)
combined.ace = runACTIONet(combined.ace, k_max = 40)

readr::write_rds(combined.ace, "~/BD/results/datasets/ACTIONet_v3.rds")

```

```{r}
l2 = infer.missing.cell.labels(combined.ace, combined.ace$Celltype)


plot.ACTIONet(combined.ace, combined.ace$Celltype_inferred, palette = celltype_colors)
plot.ACTIONet(combined.ace, l2, palette = celltype_colors)


CC = cor(combined.ace$unified_feature_specificity, ACTIONet_summary$unified_feature_specificity, method = "pearson")
M = as(MWM_hungarian(1+CC), "dgTMatrix")

# X = CC
# X[X < 0] = 0
# Heatmap(X[M@i+1, M@j+1], cluster_rows = F, cluster_columns = F)



```


```{r}

```


```{r}
tl = compute_archetype_core_centrality(combined.ace$ACTIONet, combined.ace$Celltype_inferred)
gg = plot.ACTIONet(combined.ace, combined.ace$Celltype_inferred, point_size = 0.3, palette = cols, trans_attr = tl, use_repel = TRUE)

png("~/BD/results/figures/ACTIONet_final_cleaned2022.png", res = 150, width = 1200, height = 900)
print(gg)
dev.off()





```

